# =========================
# Banco de dados H2 (produção)
# =========================
spring.datasource.url=jdbc:h2:mem:biblioteca
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criação automática das tabelas
spring.jpa.hibernate.ddl-auto=create-drop

# Executar sempre o data.sql após criar as tabelas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Mostrar SQL no console
spring.jpa.show-sql=true

# =========================
# Console H2
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# Configuração do servidor
# =========================
server.port=8080

# =========================
# Configuração de e-mail (CompraService)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projetosesolucoestec2026@gmail.com
spring.mail.password=rjqm sojy xybr dxek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
