# Banco H2 para testes
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza tabelas sem recriar
spring.jpa.hibernate.ddl-auto=update

# Não rodar data.sql nos testes
spring.sql.init.mode=never

spring.jpa.show-sql=false

# Mock de e-mail para não quebrar nos testes
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=test
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
