# Porta do servidor
server.port=8080

# Banco de dados H2 em memória
spring.datasource.url=jdbc:h2:mem:progwebdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Configuração de envio de e-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projetosesolucoestec2026@gmail.com
spring.mail.password=rjqm sojy xybr dxek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
